from __future__ import annotations

from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def generate_invoice_pdf(data: dict[str, str | float], output_path: Path) -> Path:
	output_path.parent.mkdir(parents=True, exist_ok=True)
	c = canvas.Canvas(str(output_path), pagesize=A4)
	width, height = A4

	c.setFont("Helvetica-Bold", 18)
	c.drawString(50, height - 60, "INVOICE")

	c.setFont("Helvetica", 11)
	c.drawString(50, height - 95, f"Invoice Number: {data.get('invoice_number', '-')}")
	c.drawString(50, height - 115, f"Issue Date: {data.get('issue_date', '-')}")
	c.drawString(50, height - 135, f"Due Date: {data.get('due_date', '-')}")

	c.drawString(50, height - 175, f"From: {data.get('freelancer_name', '-')}")
	c.drawString(50, height - 195, f"To: {data.get('client_name', '-')}")

	c.line(50, height - 225, width - 50, height - 225)
	c.drawString(50, height - 245, f"Service: {data.get('service_description', '-')}")
	c.drawString(50, height - 265, f"Amount: INR {data.get('amount', 0.0)}")
	c.drawString(50, height - 285, f"GST Rate: {data.get('gst_rate', 18)}%")
	c.drawString(50, height - 305, f"GST Amount: INR {data.get('gst_amount', 0.0)}")

	c.setFont("Helvetica-Bold", 12)
	c.drawString(50, height - 340, f"Total Payable: INR {data.get('invoice_total', 0.0)}")

	c.setFont("Helvetica", 10)
	c.drawString(50, 60, "Generated by Freelance Tax MCP")
	c.showPage()
	c.save()
	return output_path

